# Generated by Django 4.2.5 on 2024-05-17 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('june_publishing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='series',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='june_publishing.bookseries'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='june_publishing.category'),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='june_publishing.language'),
        ),
        migrations.AlterField(
            model_name='book',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='june_publishing.level'),
        ),
        migrations.AlterField(
            model_name='book',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='june_publishing.subject'),
        ),
        migrations.AlterField(
            model_name='bookseries',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_series', to='june_publishing.language'),
        ),
        migrations.AlterField(
            model_name='bookseries',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_series', to='june_publishing.level'),
        ),
        migrations.AlterField(
            model_name='bookseries',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_series', to='june_publishing.subject'),
        ),
    ]
