# Generated by Django 4.2.5 on 2024-05-09 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('june_publishing', '0002_alter_bookimage_for_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.TextField(),
        ),
    ]
