# Generated by Django 4.2.5 on 2024-05-17 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('june_publishing', '0002_book_series_alter_book_category_alter_book_language_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seriesmaterial',
            old_name='series_materials',
            new_name='series_material',
        ),
        migrations.AlterField(
            model_name='book',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='june_publishing.bookseries'),
        ),
    ]
