# Generated by Django 4.2.5 on 2024-05-20 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('june_publishing', '0003_rename_series_materials_seriesmaterial_series_material_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='date',
        ),
        migrations.RemoveField(
            model_name='book',
            name='language',
        ),
        migrations.RemoveField(
            model_name='book',
            name='level',
        ),
        migrations.RemoveField(
            model_name='book',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='book',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='book',
            name='version',
        ),
    ]
