# Generated by Django 4.2.5 on 2024-05-09 20:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('june_publishing', '0003_alter_book_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='key_features',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
    ]
