# Generated by Django 4.2.5 on 2024-05-31 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('june_publishing', '0004_remove_book_author_remove_book_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
    ]
