# Generated by Django 4.2.5 on 2024-05-10 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('june_publishing', '0004_alter_book_key_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pdf_url',
            field=models.URLField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='bookimage',
            name='image_url',
            field=models.URLField(max_length=5000),
        ),
    ]
