# Generated by Django 4.2.5 on 2024-05-10 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('june_publishing', '0005_alter_book_pdf_url_alter_bookimage_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='june_publishing.category'),
        ),
        migrations.AlterField(
            model_name='book',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='june_publishing.level'),
        ),
    ]
