# Generated by Django 4.2.5 on 2024-06-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('june_publishing', '0006_remove_level_level_level_ar_level_en'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category',
        ),
        migrations.RemoveField(
            model_name='seriesmaterial',
            name='series_material',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='subject',
        ),
        migrations.AddField(
            model_name='category',
            name='ar',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='en',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='seriesmaterial',
            name='ar',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='seriesmaterial',
            name='en',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='ar',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='en',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
