# Generated by Django 4.2.5 on 2024-06-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('june_publishing', '0007_remove_category_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='ar',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='level',
            name='en',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
