# Generated by Django 4.2.5 on 2024-06-12 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('june_publishing', '0008_alter_level_ar_alter_level_en'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
