# Generated by Django 4.2.5 on 2024-06-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('june_publishing', '0009_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='ar',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='level',
            name='en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='seriesmaterial',
            name='ar',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='seriesmaterial',
            name='en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='ar',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='en',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
