# Generated by Django 4.2.5 on 2024-06-12 16:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('june_publishing', '0010_alter_level_ar_alter_level_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookseries',
            old_name='features',
            new_name='features_ar',
        ),
        migrations.RemoveField(
            model_name='book',
            name='title',
        ),
        migrations.RemoveField(
            model_name='bookseries',
            name='author',
        ),
        migrations.RemoveField(
            model_name='bookseries',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='bookseries',
            name='title',
        ),
        migrations.RemoveField(
            model_name='bookseries',
            name='version',
        ),
        migrations.AddField(
            model_name='book',
            name='title_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bookseries',
            name='author_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bookseries',
            name='author_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bookseries',
            name='features_en',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='bookseries',
            name='summary_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='bookseries',
            name='summary_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='bookseries',
            name='title_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bookseries',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bookseries',
            name='version_ar',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='bookseries',
            name='version_en',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
