# Generated by Django 4.2.5 on 2024-06-12 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('june_publishing', '0011_rename_features_bookseries_features_ar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookseries',
            name='version_ar',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bookseries',
            name='version_en',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
